-- *** SqlDbx Personal Edition ***
-- !!! Not licensed for commercial use beyound 90 days evaluation period !!!
-- For version limitations please check http://www.sqldbx.com/personal_edition.htm
-- Number of queries executed: 2513, number of rows retrieved: 98578

DROP VIEW IF EXISTS adempiere.tf_weighmententry_view;

CREATE OR REPLACE VIEW adempiere.tf_weighmententry_view AS
 SELECT tf_weighmententry.tf_weighmententry_id,
    tf_weighmententry.ad_client_id,
    tf_weighmententry.ad_org_id,
    tf_weighmententry.isactive,
    tf_weighmententry.created,
    tf_weighmententry.createdby,
    tf_weighmententry.updated,
    tf_weighmententry.updatedby,
    tf_weighmententry.documentno,
    tf_weighmententry.processed,
    tf_weighmententry.status,
    tf_weighmententry.weighmententrytype,
    tf_weighmententry.c_bpartner_id,
    tf_weighmententry.tf_quarry_id,
    tf_weighmententry.c_project_id,
    tf_weighmententry.vehicleno,
    tf_weighmententry.tf_rentedvehicle_id,
    tf_weighmententry.m_product_id,
    tf_weighmententry.tareweight,
    tf_weighmententry.tareweighttime,
    tf_weighmententry.grossweight,
    tf_weighmententry.grossweighttime,
    tf_weighmententry.netweight,
    tf_weighmententry.username,
    tf_weighmententry.tf_weighmententry_uu,
    tf_weighmententry.c_order_id,
    tf_weighmententry.tf_boulder_receipt_id,
    tf_weighmententry.description,
    tf_weighmententry.tf_destination_id,
    tf_weighmententry.paymentrule,
    tf_weighmententry.m_warehouse_id,
    tf_weighmententry.ismanual,
    tf_weighmententry.tf_vehicletype_id,
    tf_weighmententry.hasbalance,
    tf_weighmententry.price,
    tf_weighmententry.mdpno,
    tf_weighmententry.permitissuedqty,
    tf_weighmententry.amount,
    tf_weighmententry.partyname,
    tf_weighmententry.phone,
    tf_weighmententry.tf_send_to,
    tf_weighmententry.tf_productionplant_id,
    tf_weighmententry.tf_bluemetal_type,
    tf_weighmententry.netweightunit,
    tf_weighmententry.c_uom_id,
    tf_weighmententry.c_orderline_id,
    tf_weighmententry.rent_amt,
    tf_weighmententry.drivertips,
    tf_weighmententry.totalamt,
    tf_weighmententry.invoiceno,
    tf_weighmententry.permitpassamount,
    tf_weighmententry.passqtyissued,
    tf_weighmententry.passpriceperunit,
    tf_weighmententry.tenderamount,
    tf_weighmententry.changeamt,
    tf_weighmententry.newdestination,
    tf_weighmententry.m_product2_id,
    tf_weighmententry.ispermitsales,
    tf_weighmententry.billingname,
    tf_weighmententry.drivername,
    tf_weighmententry.roundingoff,
    tf_weighmententry.discountamount,
    tf_weighmententry.completedby,
    tf_weighmententry.gstamount,
    tf_weighmententry.newproduct,
    tf_weighmententry.tpno,
    tf_weighmententry.tf_weighmententryprimary_id,
    tf_weighmententry.issecondary,
    tf_weighmententry.invoicetype,
    tf_weighmententry.royaltyno,
    tf_weighmententry.ewaybillno,
    tf_weighmententry.primarydocumentno,
    tf_weighmententry.tf_pricelistuom_id,
    tf_weighmententry.isroyaltypassinclusive,
    tf_weighmententry.isrentinclusive,
    tf_weighmententry.istaxincluded,
    tf_weighmententry.ispriceconfidential,
    tf_weighmententry.c_bpartnerwb_id,
    tf_weighmententry.freightrule_id,
    tf_weighmententry.freightprice,
    tf_weighmententry.drivercontact,
    tf_weighmententry.invoiceno2,
    tf_weighmententry.createtwoinvoices,
    tf_weighmententry.tf_dispenseplanline_id,
    tf_weighmententry.shipmentto,
    NULL::unknown AS generate_salesentry,
    NULL::unknown AS print_challan,
    1000212 AS ad_table_id,
    tf_weighmententry.tf_weighmententry_id AS record_id
   
FROM tf_weighmententry;

